import { describe, expect, it } from "vitest";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createDefaultHomePage } from "@/lib/cms/defaultHomePage";

/**
 * Keeps the API's homepage seed in step with the theme's code-defined layout.
 *
 * The homepage has to exist as a real, published CMS page so its owner can edit
 * it like any other page. Hand-porting `defaultHomePage.ts` into PHP would be
 * the duplication — two copies of the same fifteen blocks, drifting apart the
 * first time anyone touched either. Instead the TypeScript stays the single
 * source and generates the JSON the seeder reads.
 *
 * `createDefaultHomePage` is deterministic (fixed block ids; the timestamp is a
 * parameter), so the output is byte-stable and drift is just a file comparison.
 * This lives in the test suite rather than a standalone script so the check runs
 * in CI with no extra tooling — the repo has no TypeScript script runner.
 *
 *   npm test                          # fails if the seed is stale
 *   UPDATE_HOME_SEED=1 npm test       # regenerates it
 */

/** Fixed, never `new Date()`: the file must be identical on every run. */
const SEEDED_AT = "2026-07-25T00:00:00.000Z";

const SEED_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../../../../ezurr-api/database/seeders/data/home-page.json",
);

function expected(): string {
  const doc = createDefaultHomePage(SEEDED_AT);
  return `${JSON.stringify(
    {
      _generated:
        "Generated by ezurr-theme src/lib/cms/__tests__/homePageSeed.test.ts — regenerate with UPDATE_HOME_SEED=1 npm test",
      id: doc.id,
      title: doc.title,
      path: doc.path,
      snapshot: doc.draft,
    },
    null,
    2,
  )}\n`;
}

describe("homepage seed", () => {
  it("matches the layout in defaultHomePage.ts", () => {
    const want = expected();

    if (process.env.UPDATE_HOME_SEED) {
      mkdirSync(dirname(SEED_PATH), { recursive: true });
      writeFileSync(SEED_PATH, want);
    }

    expect(
      existsSync(SEED_PATH),
      `${SEED_PATH} is missing — run: UPDATE_HOME_SEED=1 npm test`,
    ).toBe(true);

    expect(
      readFileSync(SEED_PATH, "utf8"),
      "The homepage layout changed but the API's seed data was not regenerated. Run: UPDATE_HOME_SEED=1 npm test",
    ).toBe(want);
  });

  it("seeds only block types the API will accept", () => {
    // Mirrors CmsPage::BLOCK_TYPES. A seed naming a type the API rejects would
    // fail at `db:seed` time, on a fresh install, with a validation error.
    const allowed = new Set([
      "hero_slider", "assurance_strip", "product_rail", "offer_banner",
      "brand_explorer", "editorial_banner", "digital_cards", "category_showcase",
      "row", "column", "rich_text", "legal_doc", "overlay_stage",
      "custom_html", "widget",
    ]);
    const types: string[] = [];
    const walk = (blocks: { type: string; children?: unknown[] }[]) => {
      for (const b of blocks) {
        types.push(b.type);
        if (Array.isArray(b.children)) {
          walk(b.children as { type: string; children?: unknown[] }[]);
        }
      }
    };
    for (const v of createDefaultHomePage(SEEDED_AT).draft.variants) {
      walk(v.sections);
    }
    expect(types.length).toBeGreaterThan(0);
    expect(types.filter((t) => !allowed.has(t))).toEqual([]);
  });
});
