import type { CmsWidgetDefinition } from "./types";

/** Seed marketplace catalog — installs flip `installed` / `enabled` in the store. */
export function createWidgetCatalogSeed(): CmsWidgetDefinition[] {
  return [
    {
      id: "wgt-countdown",
      name: "Launch countdown",
      description: "Big countdown clock for release day hype.",
      category: "Marketing",
      author: "Ezurr Labs",
      version: "1.0.0",
      installed: false,
      enabled: false,
      icon: "⏱",
      defaults: { title: "Drops in", targetLabel: "Release day" },
      fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "targetLabel", label: "Subtitle", type: "text" },
      ],
      templateHtml:
        '<section class="ez-page py-12 text-center"><p class="ez-mono text-[10px] uppercase tracking-[0.16em] text-[#86868B]">{{title}}</p><p class="mt-3 text-4xl font-semibold tracking-[-0.04em] text-[#1D1D1F]">{{targetLabel}}</p><p class="mt-4 ez-mono text-sm text-[#6E6E73]">00d · 12h · 34m · 56s</p></section>',
      templateCss: "",
    },
    {
      id: "wgt-trust",
      name: "Trust badges",
      description: "Compact authenticity and shipping badges.",
      category: "Marketing",
      author: "Ezurr Labs",
      version: "1.0.0",
      installed: true,
      enabled: true,
      icon: "✓",
      defaults: { line: "Genuine · Sealed · Warranty-backed · Fast dispatch" },
      fields: [{ key: "line", label: "Badge line", type: "text" }],
      templateHtml:
        '<section class="ez-page py-6"><div class="rounded-full border border-black/[0.08] bg-[#F5F5F7] px-5 py-3 text-center text-sm font-medium text-[#1D1D1F]">{{line}}</div></section>',
    },
    {
      id: "wgt-newsletter",
      name: "Newsletter signup",
      description: "Email capture strip for drops and restocks.",
      category: "Marketing",
      author: "Ezurr Labs",
      version: "1.1.0",
      installed: false,
      enabled: false,
      icon: "✉",
      defaults: {
        title: "Never miss a drop.",
        placeholder: "Mobile or email",
        cta: "Notify me",
      },
      fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "placeholder", label: "Placeholder", type: "text" },
        { key: "cta", label: "Button", type: "text" },
      ],
      templateHtml:
        '<section class="ez-page py-12"><div class="flex flex-col gap-4 rounded-[28px] border border-black/[0.07] bg-white p-8 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="text-2xl font-semibold tracking-[-0.03em]">{{title}}</h3></div><form class="flex w-full max-w-md gap-2" onsubmit="return false"><input class="min-h-11 flex-1 rounded-full border border-black/[0.1] px-4 text-sm" placeholder="{{placeholder}}" /><button class="min-h-11 rounded-full bg-[#1D1D1F] px-5 text-sm font-semibold text-white">{{cta}}</button></form></div></section>',
    },
    {
      id: "wgt-faq",
      name: "FAQ accordion",
      description: "Common questions in a compact stack.",
      category: "Content",
      author: "Community",
      version: "1.0.2",
      installed: false,
      enabled: false,
      icon: "?",
      defaults: {
        q1: "When do I pay for a pre-order?",
        a1: "Reserve now; pay at release for eligible titles.",
        q2: "Are products genuine?",
        a2: "Yes — sealed and warranty-backed.",
      },
      fields: [
        { key: "q1", label: "Question 1", type: "text" },
        { key: "a1", label: "Answer 1", type: "textarea" },
        { key: "q2", label: "Question 2", type: "text" },
        { key: "a2", label: "Answer 2", type: "textarea" },
      ],
      templateHtml:
        '<section class="ez-page py-12 space-y-3"><details class="rounded-2xl border border-black/[0.08] bg-white p-5" open><summary class="cursor-pointer font-semibold">{{q1}}</summary><p class="mt-2 text-sm text-[#6E6E73]">{{a1}}</p></details><details class="rounded-2xl border border-black/[0.08] bg-white p-5"><summary class="cursor-pointer font-semibold">{{q2}}</summary><p class="mt-2 text-sm text-[#6E6E73]">{{a2}}</p></details></section>',
    },
    {
      id: "wgt-video",
      name: "Video embed",
      description: "Responsive 16:9 media frame.",
      category: "Content",
      author: "Ezurr Labs",
      version: "1.0.0",
      installed: false,
      enabled: false,
      icon: "▶",
      defaults: {
        title: "Watch the trailer",
        note: "Embed URL configured in inspector (demo frame).",
      },
      fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "note", label: "Note", type: "text" },
      ],
      templateHtml:
        '<section class="ez-page py-12"><h3 class="mb-4 text-xl font-semibold">{{title}}</h3><div class="aspect-video overflow-hidden rounded-[24px] bg-[#101012] grid place-items-center text-white/60 text-sm">{{note}}</div></section>',
    },
    {
      id: "wgt-announce",
      name: "Announcement bar",
      description: "Slim site-wide promo strip.",
      category: "Marketing",
      author: "Ezurr Labs",
      version: "1.0.0",
      installed: true,
      enabled: true,
      icon: "!",
      defaults: { text: "Prepaid saves extra on pre-orders · Limited stock alerts live" },
      fields: [{ key: "text", label: "Message", type: "text" }],
      templateHtml:
        '<div class="bg-[#1D1D1F] px-4 py-2.5 text-center text-[12px] font-medium text-white">{{text}}</div>',
    },
    {
      id: "wgt-testimonials",
      name: "Testimonials",
      description: "Three customer quotes in a row.",
      category: "Social",
      author: "Community",
      version: "1.2.0",
      installed: false,
      enabled: false,
      icon: "★",
      defaults: {
        t1: "Price locked and delivered on release day.",
        t2: "Codes arrived in under a minute.",
        t3: "Best COD experience for gaming gear.",
      },
      fields: [
        { key: "t1", label: "Quote 1", type: "textarea" },
        { key: "t2", label: "Quote 2", type: "textarea" },
        { key: "t3", label: "Quote 3", type: "textarea" },
      ],
      templateHtml:
        '<section class="ez-page py-12 grid gap-4 md:grid-cols-3"><blockquote class="rounded-[24px] border border-black/[0.07] bg-white p-6 text-sm leading-relaxed text-[#3A3A3C]">“{{t1}}”</blockquote><blockquote class="rounded-[24px] border border-black/[0.07] bg-white p-6 text-sm leading-relaxed text-[#3A3A3C]">“{{t2}}”</blockquote><blockquote class="rounded-[24px] border border-black/[0.07] bg-white p-6 text-sm leading-relaxed text-[#3A3A3C]">“{{t3}}”</blockquote></section>',
    },
    {
      id: "wgt-instagram",
      name: "Social grid",
      description: "Placeholder Instagram-style mosaic.",
      category: "Social",
      author: "Community",
      version: "0.9.0",
      installed: false,
      enabled: false,
      icon: "▦",
      defaults: { title: "From the community" },
      fields: [{ key: "title", label: "Title", type: "text" }],
      templateHtml:
        '<section class="ez-page py-12"><h3 class="mb-5 text-xl font-semibold">{{title}}</h3><div class="grid grid-cols-2 gap-3 sm:grid-cols-4">{{#tiles}}<div class="aspect-square rounded-2xl bg-[#F0F0F2]"></div>{{/tiles}}</div></section>'.replace(
          "{{#tiles}}<div class=\"aspect-square rounded-2xl bg-[#F0F0F2]\"></div>{{/tiles}}",
          '<div class="aspect-square rounded-2xl bg-[#F0F0F2]"></div><div class="aspect-square rounded-2xl bg-[#E8E8ED]"></div><div class="aspect-square rounded-2xl bg-[#F0F0F2]"></div><div class="aspect-square rounded-2xl bg-[#E8E8ED]"></div>',
        ),
    },
    {
      id: "wgt-spacer",
      name: "Spacer",
      description: "Vertical breathing room.",
      category: "Content",
      author: "Ezurr Labs",
      version: "1.0.0",
      installed: true,
      enabled: true,
      icon: "↕",
      defaults: { height: 48 },
      fields: [{ key: "height", label: "Height (px)", type: "number" }],
      templateHtml: '<div style="height:{{height}}px" aria-hidden="true"></div>',
    },
    {
      id: "wgt-cta",
      name: "CTA band",
      description: "Centered call-to-action with button.",
      category: "Marketing",
      author: "Ezurr Labs",
      version: "1.0.0",
      installed: false,
      enabled: false,
      icon: "→",
      defaults: {
        title: "Ready to reserve?",
        cta: "Shop pre-orders",
        href: "/preorders",
      },
      fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "cta", label: "Button", type: "text" },
        { key: "href", label: "URL", type: "url" },
      ],
      templateHtml:
        '<section class="ez-page py-14 text-center"><h3 class="text-3xl font-semibold tracking-[-0.04em]">{{title}}</h3><a href="{{href}}" class="mt-6 inline-flex min-h-11 items-center rounded-full bg-[#1D1D1F] px-6 text-sm font-semibold text-white">{{cta}}</a></section>',
    },
  ];
}
